/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import mycode.DBconnect;
import mycode.Validation;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Janith
 */
public class customer_order extends javax.swing.JInternalFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rst=null;
Validation v=new Validation();
String errorMeassage="";
    /**
     * Creates new form customer_order
     */
    public customer_order() {
        initComponents();
        conn=DBconnect.connect();
        //table();
        fill_comb();
        showDate();
    }
public void table()
    {
        try {
         String sql= "SELECT * FROM order_details";
         pst=conn.prepareStatement(sql);
         rst=pst.executeQuery();
         
         otable.setModel(DbUtils.resultSetToTableModel(rst));
         
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    
    }

void showDate()
            {
                Date d=new Date();
                SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd");
                Order_date.setText(s.format(d));
                
            
            }
public void fill_comb()
{
    try {
        String q="Select * from product";
        pst=conn.prepareStatement(q);
        rst=pst.executeQuery();
        while(rst.next())
        {
           String id=rst.getString("id");
           avilableproduct.addItem(id);
        
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        aquan = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        pname = new javax.swing.JTextField();
        avilableproduct = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        otable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        quan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Order_date = new javax.swing.JLabel();
        order_no = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        uquan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("View_Orders");
        setPreferredSize(new java.awt.Dimension(845, 494));

        jPanel1.setPreferredSize(new java.awt.Dimension(845, 494));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Product_No");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 120, 100, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Product_Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 180, 110, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Available_Quantity");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 230, 140, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Price(Unit)");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 330, 130, 17);

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/system-software-update-icon.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(250, 380, 140, 25);

        aquan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aquan.setForeground(new java.awt.Color(255, 0, 51));
        aquan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aquanActionPerformed(evt);
            }
        });
        jPanel1.add(aquan);
        aquan.setBounds(220, 230, 170, 30);

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price);
        price.setBounds(220, 330, 170, 30);

        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        jPanel1.add(pname);
        pname.setBounds(220, 170, 170, 30);

        avilableproduct.setBackground(new java.awt.Color(255, 204, 0));
        avilableproduct.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        avilableproduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available_Product" }));
        avilableproduct.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                avilableproductPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        avilableproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avilableproductActionPerformed(evt);
            }
        });
        jPanel1.add(avilableproduct);
        avilableproduct.setBounds(220, 110, 170, 30);

        jButton2.setBackground(new java.awt.Color(255, 204, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jButton2.setText("Create_Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(250, 420, 140, 30);

        jButton4.setBackground(new java.awt.Color(255, 204, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/-Close-icon.png"))); // NOI18N
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(60, 420, 140, 30);

        otable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product_No", "Product_Name", "quantity"
            }
        ));
        otable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                otableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(otable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(400, 130, 430, 210);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Customer_NO");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 70, 110, 17);
        jPanel1.add(nic);
        nic.setBounds(220, 60, 170, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Select_Quantity");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 280, 130, 17);

        quan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanActionPerformed(evt);
            }
        });
        jPanel1.add(quan);
        quan.setBounds(220, 280, 170, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("Order_No");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 30, 90, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Date");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(530, 20, 50, 17);

        Order_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Order_date.setText("jLabel9");
        jPanel1.add(Order_date);
        Order_date.setBounds(620, 20, 150, 17);
        jPanel1.add(order_no);
        order_no.setBounds(220, 20, 170, 30);

        jButton5.setBackground(new java.awt.Color(255, 204, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton5.setText("ADD_Product");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(60, 380, 140, 25);
        jPanel1.add(uquan);
        uquan.setBounds(620, 90, 160, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Quantity");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(530, 100, 80, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/yellow_background_by_originalpsdcom-d6wbg8x.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 835, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public boolean validateInputs()
    {
        errorMeassage="";
        if(!v.requiredFieldValidator(order_no))
        {
           errorMeassage=errorMeassage+"\nOrder Number should not be empty";
        }
        if(!v.numericValidator(order_no))
        {
        errorMeassage=errorMeassage+"\nOrder Number should be numeric";
        }
        if(!v.requiredFieldValidator(quan))
        {
           errorMeassage=errorMeassage+"\nQuantity should not be empty";
        }
         
        
       /*  if(!v.lengthValider(nic,10,10))
        {
           errorMeassage=errorMeassage+"\nNIC between 1-10";
        }*/
         if(errorMeassage.equals(""))
         {return true;
         }
         else{return false;}
    }
    
    private void aquanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aquanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aquanActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void avilableproductPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_avilableproductPopupMenuWillBecomeInvisible
        String temp=(String)avilableproduct.getSelectedItem();
        int counter=0; 
        int squan=0;
        String sql= "select * from product where id=?";
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1, temp);
            rst=pst.executeQuery();
            while(rst.next())
            {
             String name=rst.getString("name");
             pname.setText(name);
             String aquantity=rst.getString("quantity");
             while(counter<otable.getRowCount())
             {
                 if(otable.getValueAt(counter, 0).toString().equals(temp))
                     //checking whether selected product number and existing product number equal
                 {
                     squan=squan+Integer.parseInt(otable.getValueAt(counter, 2).toString());
                     //existing quantity assignt to the variable
                 }
                 counter++;
             }
             if(squan==0)
             {
                 aquan.setText(aquantity);
             }
             else
             {
                 aquan.setText(String.valueOf(Integer.parseInt(aquantity)-squan));
             }
             
             String pri=rst.getString("price");
             price.setText(pri);
             
            }
        } catch (Exception e) {JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_avilableproductPopupMenuWillBecomeInvisible

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                String ornum=order_no.getText();
                String num=nic.getText();
                
                String pno=avilableproduct.getSelectedItem().toString();
                String name=pname.getText();
                String qua=quan.getText();
                String pri=price.getText();
                String dat=Order_date.getText();
                String quantityold="";
                int tot;
             
            
                try {
                    
            String q="INSERT INTO order_header (order_no,customer_Nic,date,status ) VALUES ('"+ ornum +"', '"+ num +"', '"+ dat +"' ,'n')";
            pst=conn.prepareStatement(q);
            pst.executeUpdate();
            int rows = otable.getRowCount();
        int counter=0;
        while(counter<rows){
            String iNo = otable.getValueAt(counter, 0).toString();
           
            String qty = otable.getValueAt(counter, 2).toString();
            //getting  details from the table
            q="Insert into order_details (OrderNo,productNo,quantity) values('"+ order_no.getText() +"','"+ iNo +"','"+ qty +"')";
            //JOptionPane.showMessageDialog(this, "|"+order_no.getText()+"|"+"|"+pno+"|"+"|"+qty+"|");
            pst=conn.prepareStatement(q);
            pst.execute();
            //JOptionPane.showMessageDialog(this, jTable1.getValueAt(counter, 0)+"\t"+jTable1.getValueAt(counter, 2));
            counter++;
        }
        }
                catch (Exception e) {
              JOptionPane.showMessageDialog(null,e);
        }
            
               JOptionPane.showMessageDialog(null, "Order Created");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void quanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quanActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
            otable.setValueAt(uquan.getText(), otable.getSelectedRow(), 2);
        
         
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void otableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otableMouseClicked
        try {
                uquan.setText(otable.getValueAt(otable.getSelectedRow(), 2).toString());

        } catch (ArrayIndexOutOfBoundsException e) {
        }
        
       
    }//GEN-LAST:event_otableMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         DefaultTableModel model;
         int counter=0;
         boolean status=true;
          if(validateInputs()){ 
         model = (DefaultTableModel) otable.getModel();
            while(counter<otable.getRowCount())
            {
             //   JOptionPane.showMessageDialog(this,"1");
                if(avilableproduct.getSelectedItem().toString().equals(otable.getValueAt(counter, 0).toString()))
                    //checking whether product  exist 
                {
                    status=false;
                }
                counter++;
            }
            if(status==true)
            {
               model.addRow(new Object[]{ avilableproduct.getSelectedItem().toString(),pname.getText(),quan.getText()}); 
            }  // adding the details
            else
            {
                JOptionPane.showMessageDialog(this,"Item allready exist in the order");
            }
            aquan.setText(String.valueOf(Integer.parseInt(aquan.getText())-Integer.parseInt(quan.getText())));
            // reducing from available quantity and setting new value 
            avilableproduct.addItem(null);
            //order_no.setText(null);
            pname.setText(null); 
            quan.setText(null); 
            aquan.setText(null); 
            price.setText(null);
            avilableproduct.setSelectedIndex(0);
          } else
         JOptionPane.showMessageDialog(this,errorMeassage,"InvalideDate",JOptionPane.ERROR_MESSAGE);   
            
    }//GEN-LAST:event_jButton5ActionPerformed

    private void avilableproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avilableproductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avilableproductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Order_date;
    private javax.swing.JTextField aquan;
    private javax.swing.JComboBox<String> avilableproduct;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField order_no;
    private javax.swing.JTable otable;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quan;
    private javax.swing.JTextField uquan;
    // End of variables declaration//GEN-END:variables
}
