/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import mycode.DBconnect;
import mycode.Validation;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Janith chathurnga
 */
public class product extends javax.swing.JInternalFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rst=null;
Validation v=new Validation();
String errorMeassage="";
    /**
     * Creates new form product
     */
    public product() {
        initComponents();
        conn=DBconnect.connect();
        table();
    }
public void table()
    {
        try {
         String sql= "SELECT * FROM product";
         pst=conn.prepareStatement(sql);
         rst=pst.executeQuery();
         
         ptable.setModel(DbUtils.resultSetToTableModel(rst));
         
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    
    }


   public boolean validateInputs()
    {
        errorMeassage="";
       
        if(!v.requiredFieldValidator(t1))
        {
           errorMeassage=errorMeassage+"\nProduct_No should not be empty";
        }
        if(!v.requiredFieldValidator(t2))
       {
          errorMeassage=errorMeassage+"\nProduct Name should not be empty";
       }
        
         if(!v.requiredFieldValidator(t4))
        {
           errorMeassage=errorMeassage+"\nPrice should not be empty";
        }
        
         if(errorMeassage.equals(""))
         {return true;
         }
         else{return false;}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ptable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(845, 494));

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Product_Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 150, 110, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Quantity");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 210, 70, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Price");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 270, 34, 14);
        jPanel1.add(t4);
        t4.setBounds(150, 260, 200, 30);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel1.add(t2);
        t2.setBounds(150, 140, 200, 30);

        ptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ptableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ptable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(380, 80, 440, 200);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Product_Number");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 90, 130, 17);
        jPanel1.add(t1);
        t1.setBounds(150, 80, 200, 30);

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Add_Product");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 350, 140, 30);

        jButton3.setBackground(new java.awt.Color(255, 204, 51));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/-Close-icon.png"))); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(140, 410, 140, 31);

        jButton4.setBackground(new java.awt.Color(255, 204, 51));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(220, 350, 140, 30);

        c1.setBackground(new java.awt.Color(255, 204, 51));
        c1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Quantity", "100", "75", "50" }));
        c1.setToolTipText("");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1);
        c1.setBounds(150, 200, 200, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/yellow_background_by_originalpsdcom-d6wbg8x.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 845, 495);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     if(validateInputs()){
        if(c1.getSelectedIndex()==0){
            
         JOptionPane.showMessageDialog(null, "plz selcet quantity");
      
     }else{
              String i_d=t1.getText();
        String name_=t2.getText();
        String quan_=c1.getSelectedItem().toString();
        String price_=t4.getText();
        try {
           String q="INSERT INTO product (id,name,quantity,price) values ('"+ i_d +"', '"+ name_ +"','"+ quan_ +"','"+ price_+"')";   
           pst=conn.prepareStatement(q);
           pst.execute(q);
           table();
        
           if(c1.getSelectedIndex()==1)
           {
       
           q="update get_item set item_quantity=item_quantity-100";
            pst=conn.prepareStatement(q);
        
            pst.execute();
           }
          else if(c1.getSelectedIndex()==2)
           {
       
           q="update get_item set item_quantity=item_quantity-75";
            pst=conn.prepareStatement(q);
        
            pst.execute();
           }
           else if(c1.getSelectedIndex()==3)
           {
       
           q="update get_item set item_quantity=item_quantity-50";
            pst=conn.prepareStatement(q);
        
            pst.execute();
           }
           
          
           
         
        }catch (Exception e) {
        }
        
        }    // mee bracket eka cpmment karapn quantity null karanna kiwwoth//
     }else
         JOptionPane.showMessageDialog(this,errorMeassage,"InvalideDate",JOptionPane.ERROR_MESSAGE);   
        
            
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptableMouseClicked
        int t=ptable.getSelectedRow();
        String id=ptable.getValueAt(t, 0).toString();
        String name=ptable.getValueAt(t, 1).toString();
        String quan=ptable.getValueAt(t, 2).toString();
        String price=ptable.getValueAt(t, 3).toString();
        
        t1.setText(id);
        t2.setText(name);
        c1.setSelectedItem(quan);
        t4.setText(price);
    }//GEN-LAST:event_ptableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id=t1.getText();
        try {
            String q="Delete from product where id = '"+ id +"'";
            pst=conn.prepareStatement(q);
            pst.execute();
            table();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ptable;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
