
package Interface;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import mycode.DBconnect;
import mycode.Validation;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Janith Chathuranga
 */
public class stockkeeper extends javax.swing.JInternalFrame {
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rst=null;
    Validation v=new Validation();
    String errorMeassage="";
    /**
     * Creates new form stockkeeper
     */
    public stockkeeper() {
        initComponents();
        conn=DBconnect.connect();
        table();
    }
public void table()
{
    try {
        String q="Select * from stockkeeper";
        pst=conn.prepareStatement(q);
        rst=pst.executeQuery();
        stable.setModel(DbUtils.resultSetToTableModel(rst));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Stock_Keeper_Register");
        setPreferredSize(new java.awt.Dimension(845, 494));

        jPanel1.setPreferredSize(new java.awt.Dimension(845, 494));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 60, 40, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 110, 50, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Age");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 160, 40, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 210, 60, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("E-mail");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 300, 50, 20);
        jPanel1.add(t1);
        t1.setBounds(170, 50, 190, 30);
        jPanel1.add(t2);
        t2.setBounds(170, 100, 190, 30);
        jPanel1.add(t3);
        t3.setBounds(170, 150, 190, 30);

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        jPanel1.add(t4);
        t4.setBounds(170, 200, 190, 30);
        jPanel1.add(t5);
        t5.setBounds(170, 300, 190, 30);
        jPanel1.add(t6);
        t6.setBounds(170, 250, 190, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Tel");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 260, 30, 20);

        jButton2.setBackground(new java.awt.Color(255, 204, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/system-software-update-icon.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 350, 160, 40);

        jButton3.setBackground(new java.awt.Color(255, 204, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/remove-icon.png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(60, 410, 160, 40);

        jButton5.setBackground(new java.awt.Color(255, 204, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/user-add-icon.png"))); // NOI18N
        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(60, 350, 160, 40);

        jButton4.setBackground(new java.awt.Color(255, 204, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/-Close-icon.png"))); // NOI18N
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(270, 410, 160, 40);

        stable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        stable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(370, 50, 440, 280);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Go-back-icon.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 10, 40, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/yellow_background_by_originalpsdcom-d6wbg8x.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 845, 494);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     public boolean validateInputs()
    {
        errorMeassage="";
        if(!v.requiredFieldValidator(t1))
        {
           errorMeassage=errorMeassage+"\nId should not be empty";
        }
        if(!v.numericValidator(t1))
        {
        errorMeassage=errorMeassage+"\nId should be numeric";
        }
        if(!v.requiredFieldValidator(t2))
        {
           errorMeassage=errorMeassage+"\nName should not be empty";
        }
         if(!v.requiredFieldValidator(t3))
        {
           errorMeassage=errorMeassage+"\nAge should not be empty";
        }
          if(!v.numericValidator(t3))
        {
           errorMeassage=errorMeassage+"\nAge should  be numeric";
        }
           if(!v.rangeValider(t3,10,99))
        {
           errorMeassage=errorMeassage+"\nAge between 10-99";
        }
           if(!v.requiredFieldValidator(t4))
        {
           errorMeassage=errorMeassage+"\nAddress should not be empty";
        }
           
           if(!v.requiredFieldValidator(t5))
        {
           errorMeassage=errorMeassage+"\nE-mail should not be empty";
        }
           
           
         if(!v.numericValidator(t6))
        {
           errorMeassage=errorMeassage+"\nTel should  be numeric";
        }
         if(!v.lengthValider(t6,10,10))
        {
           errorMeassage=errorMeassage+"\nTel between 1-10";
        }
         if(errorMeassage.equals(""))
         {return true;
         }
         else{return false;}
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int v=JOptionPane.showConfirmDialog(null, "Do you really want to Update");
        if(v==0){
             if(validateInputs()){
        String id = t1.getText();
        String name = t2.getText();
        String age =t3.getText();
        String add =t4.getText();
        String tel = t6.getText();
         String email = t5.getText();
        
        JOptionPane.showMessageDialog(null,"updated ");
        try {
            String q="Update stockkeeper set name = '"+ name +"', age = '"+ age +"', address = '"+ add +"', tel = '"+ tel +"', email = '"+ email +"' where id = '"+ id +"'";
            pst=conn.prepareStatement(q);
            pst.execute();
            table();
        } catch (Exception e) {
        } 
             }else
         JOptionPane.showMessageDialog(this,errorMeassage,"InvalideDate",JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void stableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stableMouseClicked
        int y=stable.getSelectedRow();
        String id=stable.getValueAt(y, 0).toString();
        String name=stable.getValueAt(y, 1).toString();
        String age=stable.getValueAt(y, 2).toString();
        String add=stable.getValueAt(y, 3).toString();
        String tel=stable.getValueAt(y, 4).toString();
        String email=stable.getValueAt(y, 5).toString();
        
        
        t1.setText(id);
        t2.setText(name);
        t3.setText(age);
        t4.setText(add);
        t6.setText(tel);
        t5.setText(email);
    }//GEN-LAST:event_stableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String id=t1.getText();
        int y=JOptionPane.showConfirmDialog(null, "Do you really want to Delete");
        if(y==0)
        {
            try {
                 String q="Delete from stockkeeper where id = '"+ id +"'";
                 pst=conn.prepareStatement(q);
                 pst.execute();
                 table();
                 JOptionPane.showMessageDialog(null, "Success");
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       int y=JOptionPane.showConfirmDialog(null, "Do you really want to Cancel");
        if(y==0)
        {
          this.dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.dispose();
        //Manager m=new Manager();
        //m.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if(validateInputs()){

            String id = t1.getText();
            String name = t2.getText();
            String age =t3.getText();
            String add =t4.getText();
            String tel = t6.getText();
            String email = t5.getText();

            try{
                String y="INSERT INTO stockkeeper (id,name,age,address,tel,email) values ('"+ id +"', '"+ name +"','"+ age +"', '"+ add +"', '"+ tel +"', '"+ email +"')";
                pst = conn.prepareStatement(y);
                pst.execute();

                table();
                JOptionPane.showMessageDialog(null, "success");

            }catch(Exception e){}

        }else
        JOptionPane.showMessageDialog(this,errorMeassage,"InvalideDate",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable stable;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
