/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Class.suplier;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import mycode.DBconnect;
import mycode.DbConnection;
import mycode.Validation;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Janith
 */
public class supplier extends javax.swing.JInternalFrame {
   // Connection conn=null;
    Connection conn= null;
    PreparedStatement pst=null;
    ResultSet rst=null;
    Validation v=new Validation();
    String errorMeassage="";
    /**
     * Creates new form supplier
     */
    public supplier() {
        initComponents();
        conn=DBconnect.connect();
        table();
    }
    
    public void table()
    {
        try {
         String sql= "SELECT * FROM supplier";
         pst=conn.prepareStatement(sql);
         rst=pst.executeQuery();
         
         supp.setModel(DbUtils.resultSetToTableModel(rst));
         
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        supp = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Supplier_Register");
        setPreferredSize(new java.awt.Dimension(845, 494));

        jPanel1.setPreferredSize(new java.awt.Dimension(845, 494));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 50, 30, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 100, 50, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Age");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 150, 40, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 210, 70, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Tel");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 260, 50, 17);
        jPanel1.add(t1);
        t1.setBounds(140, 50, 200, 30);
        jPanel1.add(t2);
        t2.setBounds(140, 100, 200, 30);
        jPanel1.add(t3);
        t3.setBounds(140, 150, 200, 30);

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        jPanel1.add(t4);
        t4.setBounds(140, 200, 200, 30);

        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        jPanel1.add(t7);
        t7.setBounds(140, 290, 200, 30);

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        jPanel1.add(t5);
        t5.setBounds(140, 250, 200, 30);

        supp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title  5"
            }
        ));
        supp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(supp);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(390, 50, 430, 230);

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Save-icon.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 340, 160, 40);

        jButton2.setBackground(new java.awt.Color(255, 204, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/system-software-update-icon.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(240, 340, 160, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Email");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(50, 300, 36, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Tel");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 260, 50, 17);

        jButton3.setBackground(new java.awt.Color(255, 204, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/-Close-icon.png"))); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(240, 400, 160, 40);

        jButton4.setBackground(new java.awt.Color(255, 204, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/remove-icon.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(50, 400, 160, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("Tel");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(60, 260, 50, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Go-back-icon.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 10, 40, 30);
        jPanel1.add(t6);
        t6.setBounds(140, 250, 200, 30);

        Email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/yellow_background_by_originalpsdcom-d6wbg8x.jpg"))); // NOI18N
        jPanel1.add(Email);
        Email.setBounds(0, 0, 845, 494);

        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        jPanel1.add(t8);
        t8.setBounds(140, 250, 200, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Tel");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 260, 50, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Tel");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 270, 50, 17);

        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 300, 40, 14);

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 310, 34, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validateInputs()
    {
        errorMeassage="";
        if(!v.requiredFieldValidator(t1))
        {
           errorMeassage=errorMeassage+"\nId should not be empty";
        }
        if(!v.numericValidator(t1))
        {
        errorMeassage=errorMeassage+"\nId should be numeric";
        }
        if(!v.requiredFieldValidator(t2))
        {
           errorMeassage=errorMeassage+"\nName should not be empty";
        }
         if(!v.requiredFieldValidator(t3))
        {
           errorMeassage=errorMeassage+"\nAge should not be empty";
        }
          if(!v.numericValidator(t3))
        {
           errorMeassage=errorMeassage+"\nAge should  be numeric";
        }
           if(!v.rangeValider(t3,10,99))
        {
           errorMeassage=errorMeassage+"\nAge between 10-99";
        }if(!v.requiredFieldValidator(t4))
        {
           errorMeassage=errorMeassage+"\nAddress should not be empty";
        }
        if(!v.requiredFieldValidator(t7))
        {
           errorMeassage=errorMeassage+"\nemail should not be empty";
        }
        
         if(!v.numericValidator(t5))
        {
           errorMeassage=errorMeassage+"\nTel should  be numeric";
        }
         if(!v.lengthValider(t5,10,10))
        {
           errorMeassage=errorMeassage+"\nTel between 1-10";
        }
         if(errorMeassage.equals(""))
         {return true;
         }
         else{return false;}
    }
    
    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        
         if(validateInputs()){
        
        String id = t1.getText();
        String name = t2.getText();
        String age =t3.getText();
        String add =t4.getText();
        String tel = t5.getText();
        String email = t7.getText();
        
        try{
        String y="INSERT INTO supplier (id,name,age,address,tel,email) values ('"+ id +"', '"+ name +"', '"+ age +"', '"+ add +"', '"+ tel +"', '"+ email +"')";
        pst = conn.prepareStatement(y);
        pst.execute();
        
        table();
        JOptionPane.showMessageDialog(null, "success");
        
        }catch(Exception e){}
        
         }else
         JOptionPane.showMessageDialog(this,errorMeassage,"InvalideDate",JOptionPane.ERROR_MESSAGE);  
     
         
         /* if(validateInputs())
       {
        
        String id = t1.getText();
        String name = t2.getText();
        String age =t3.getText();
        String add =t4.getText();
        String tel = t5.getText();
        
        suplier s=new suplier(id,name,age,add,tel);
        if(s.addnewSupplier())
        {
            JOptionPane.showMessageDialog(this,"Success");
        }
        else
        {
            JOptionPane.showMessageDialog(this,"fail");
           
        }table();
       }
       
        }catch(Exception e){}*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
         int v=JOptionPane.showConfirmDialog(null, "Do you really want to Update");
        if(v==0){
             if(validateInputs()){
        String id = t1.getText();
        String name = t2.getText();
        String age =t3.getText();
        String add =t4.getText();
        String tel = t5.getText();
        String email = t7.getText();
        
        JOptionPane.showMessageDialog(null,"updated ");
        try {
            String q="Update supplier set name = '"+ name +"', age = '"+ age +"', address = '"+ add +"', tel = '"+ tel +"', email = '"+ email +"' where id = '"+ id +"'";
            pst=conn.prepareStatement(q);
            pst.execute();
            table();
        } catch (Exception e) {
        } }else
         JOptionPane.showMessageDialog(this,errorMeassage,"InvalideDate",JOptionPane.ERROR_MESSAGE);  
        }
        
        /*int y=JOptionPane.showConfirmDialog(null,"Do you really want to update ");
        if(y==0){
        if(validateInputs()){
        String id = t1.getText();
        String name = t2.getText();
        String age =t3.getText();
        String add =t4.getText();
        String tel = t5.getText();
        
        suplier s=new suplier(id, name, age, add, tel);
        if(s.updatesupplier())
        {
        JOptionPane.showMessageDialog(this, "succes");
        }else{
        JOptionPane.showMessageDialog(this, "fail");
        }
        table();}else
           JOptionPane.showMessageDialog(this,errorMeassage,"InvalideDate",JOptionPane.ERROR_MESSAGE);
         
 }*/ 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id=t1.getText();
        int y=JOptionPane.showConfirmDialog(null, "Do you really want to Delete");
        if(y==0)
        {
            try {
                 String q="Delete from supplier where id = '"+ id +"'";
                 pst=conn.prepareStatement(q);
                 pst.execute();
                 table();
                 JOptionPane.showMessageDialog(null, "Success");
            } catch (Exception e) {
            }
        }
        
        
        /* int x=JOptionPane.showConfirmDialog(null, "Do you really want to Delete");
        if(x==0)
        {
           String id=t1.getText();
          
           suplier s=new suplier(id);
           if(s.deletesupplier())
           {
            JOptionPane.showMessageDialog(this,"succes");
           }
           else{JOptionPane.showMessageDialog(this,"fail");}
           table();
          
        }*/
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int c=JOptionPane.showConfirmDialog(null, "Do you really want to Cancel");
        if(c==0)
        {
           this.dispose();
           //Manager m=new Manager();
           //m.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void suppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppMouseClicked
        int y=supp.getSelectedRow();
        String id=supp.getValueAt(y, 0).toString();
        String name=supp.getValueAt(y, 1).toString();
        String age=supp.getValueAt(y, 2).toString();
        String add=supp.getValueAt(y, 3).toString();
        String tel=supp.getValueAt(y, 4).toString();
        String email=supp.getValueAt(y, 5).toString();
        
        t1.setText(id);
        t2.setText(name);
        t3.setText(age);
        t4.setText(add);
        t5.setText(tel);
        t7.setText(email);
    }//GEN-LAST:event_suppMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.dispose();
        //Manager m=new Manager();
        //m.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable supp;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables
}
